
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function toast(x){let t=$("#toast")||Object.assign(document.body.appendChild(document.createElement("div")),{id:"toast",className:"toast"});t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}
function nav(){let n=store.get("theme","light");document.documentElement.dataset.theme=n;$("#theme")?.addEventListener("click",()=>{n=n==="dark"?"light":"dark";document.documentElement.dataset.theme=n;store.set("theme",n);$("#theme").textContent=n==="dark"?"☀️":"🌙"});$("#hamb")?.addEventListener("click",()=>$("#mobile").classList.toggle("open"))}
async function tools(){return fetch("data/tools.json").then(r=>r.json())}
function card(t){return `<article class="card reveal"><div class="iconBig">${t.icon}</div><span class="tag">${t.category}</span><h3>${t.title}</h3><p>${t.description}</p><div class="row"><a class="btn primary" href="${t.page}#${t.id}">استخدام الأداة</a><button class="icon fav" data-id="${t.id}">♡</button></div></article>`}
function favs(ts){let a=store.get("favorites",[]);$$(".fav").forEach(b=>{b.textContent=a.includes(b.dataset.id)?"♥":"♡";b.onclick=()=>{a=a.includes(b.dataset.id)?a.filter(x=>x!==b.dataset.id):[...a,b.dataset.id];store.set("favorites",a);b.textContent=a.includes(b.dataset.id)?"♥":"♡";toast(a.includes(b.dataset.id)?"أضيفت للمفضلة":"أزيلت")}})}
function reveal(){if(matchMedia("(prefers-reduced-motion:reduce)").matches){ $$(".reveal").forEach(x=>x.classList.add("show"));return}let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");io.unobserve(e.target)}}),{threshold:.15});$$(".reveal").forEach((e,i)=>{e.style.transitionDelay=(i%5)*80+"ms";io.observe(e)})}
document.addEventListener("DOMContentLoaded",async()=>{nav();reveal();let ts=await tools();$$("[data-grid]").forEach(g=>{let cat=g.dataset.cat,q=g.dataset.q||"";let f=ts.filter(t=>(!cat||t.category===cat)&&(!q||[t.title,t.description,...t.keywords].join(" ").toLowerCase().includes(q)));g.innerHTML=f.map(card).join("")||'<div class="box">لا توجد أدوات مطابقة.</div>';favs(ts)});let search=$("#search");if(search){let g=$("#searchGrid");search.oninput=()=>{let q=search.value.toLowerCase();g.innerHTML=ts.filter(t=>[t.title,t.description,t.category,...t.keywords].join(" ").toLowerCase().includes(q)).map(card).join("")||'<div class="box">لا توجد نتائج.</div>';favs(ts);reveal()};g.innerHTML=ts.map(card).join("");favs(ts)}})
